### ISSUE TITLE
Global parameter options

### ISSUE THREAD

**Issue by knalli** [hlsolutions/jquery-autosuggest#15]
A global option set could provide an application-wide default. This allows a much more cleaner configuration of the plugin itself.

Inspired by #14

**Comment by t3chn0r** [comment]
Any update about this one?

**Comment by knalli** [comment]
Not yet. Perhaps Eastern, but I'm not sure.

**Comment by knalli** [comment]
See 2.3

**Comment by t3chn0r** [comment]
Thanks @knalli! Works like a charm! :+1: :100:
